//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Database_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Address
    {
        public int n_AddressNo { get; set; }
        public Nullable<int> n_ClientNo { get; set; }
        public string s_Address { get; set; }
        public string s_Email { get; set; }
        public string s_Contact { get; set; }
        public string s_PAN { get; set; }
        public string s_City { get; set; }
        public string s_State { get; set; }
        public string s_PinCode { get; set; }
    
        public virtual tb_Client tb_Client { get; set; }
    }
}
